name: Training Model ML

on:
  push:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    # Menambahkan environment variable sesuai saran GitHub
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Update ke v5 (Versi terbaru)
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn

    - name: Run Model Training
      run: |
        cd MLProject
        ls -R 
        python modelling.py

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: MLProject/mlruns/