name: Training Model ML

on:
  push:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn

    - name: Run Model Training via MLflow
      run: |
        # Menggunakan perintah 'mlflow run' di dalam folder MLProject
        # Ini akan otomatis membaca file MLProject yang ada di folder tersebut
        mlflow run MLProject

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        # Menyesuaikan path hasil mlruns yang digenerate oleh MLflow
        path: mlruns/