name: Training Model ML

on:
  push:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn==1.5.2

    - name: Run Model Training via MLflow
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name="Telco_Churn_CI_Experiment"

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        # Karena kita melakukan 'cd MLProject', folder mlruns akan muncul di dalamnya
        path: MLProject/mlruns/